spring:
  application:
    name: scaleflow

  datasource:
    url: jdbc:postgresql://localhost:5432/scaleflow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
